[package]
name = "strk20_invoke_helper"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.18.0"

[[target.starknet-contract]]
name = "zkpayslip"
sierra = true
casm = true

[dev-dependencies]
snforge_std = "0.63.0"
